server:
  port: 8081
spring:
  application:
    name: toDoApp
  datasource:
    url: jdbc:h2:mem:to-do-db
    username: user-todo
    password: todoNister
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG